server {

    listen 80 ;
    index index.php index.html index.htm;
    server_name isfdown.local;


    root /var/www/html;
    error_log /var/log/nginx/project_error.log;
    access_log /var/log/nginx/project_access.log;

    client_max_body_size 256M;
    
    location / {
            # This is cool because no php is touched for static content.
            # include the "?$args" part so non-default permalinks doesn't break when using query string
            try_files $uri $uri/ /index.php?$args;
    }
     
    location ~ \.php$ {
            #NOTE: You should have "cgi.fix_pathinfo = 0;" in php.ini
            include fastcgi_params;
            fastcgi_intercept_errors on;
            #The following parameter can be also included in fastcgi_params file
            fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_pass php:9000;
            fastcgi_read_timeout 1500;
            ## TUNE buffers to avoid error ##  
            fastcgi_buffers 16 32k;
            fastcgi_buffer_size 64k;
            fastcgi_busy_buffers_size 64k;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
            expires max;
            log_not_found off;
    }

}